fresh/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^goods/', include('goods.urls', namespace='goods')),
    url(r'^order/', include('order.urls', namespace='order')),
    url(r'^shopping_cart/', include('shopping_cart.urls', namespace='shopping_cart')),
]

user/urls.py
from django.conf.urls import include, url
from user.views import *

urlpatterns = [
    url(r'^register$',register,name='register'),
    url(r'^login$',login,name='login'),
    url(r'^success$',success,name='success'),
    url(r'^result$',result,name='result'),
    url(r'^verification$', verification, name='verification'),
    url(r'^check_username$', check_username, name='check_username'),
    url(r'^check_userpwd$', check_userpwd, name='check_userpwd'),
    url(r'^check_userverification', check_userverification, name='check_userverification'),
    url(r'^user_center$',user_center,name='user_center'),
    url(r'^user_order$', user_order, name='user_order'),
    url(r'^user_address$', user_address, name='user_address'),
    url(r'^logout$', logout, name='logout'),
]

order/models.py
from django.db import models
from user.models import *

# Create your models here.

class OrderInfo(models.Model):
    oid = models.CharField(max_length = 60, primary_key = True)
    userinfo = models.ForeignKey(User)
    odate = models.DateTimeField(auto_now_add = True)
    oispay = models.BooleanField(default = False)
    ototal = models.DecimalField(max_digits = 10,decimal_places = 2)
    oaddress = models.CharField(max_length = 150,default = '')

class OrderDetailInfo(models.Model):
    goodsinfo = models.ForeignKey('goods.GoodsInfo')
    orderinfo = models.ForeignKey(OrderInfo)
    price = models.DecimalField(max_digits = 10,decimal_places =2)
    count = models.IntegerField()

user/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    uname = models.CharField(primary_key=True,max_length=20,unique=True)
    upwd = models.CharField(max_length=42)
    uemail = models.CharField(max_length =100)
    ureceive = models.CharField(max_length = 100,default = '')
    uaddress = models.CharField(max_length = 100,default = '')
    uzipcode = models.CharField(max_length = 6,default = '')
    uphone = models.CharField(max_length = 11,default = '')

    def __str__(self):
        return self.uname

user/views.py
from django.shortcuts import render
from user.models import *
from goods.models import *
from hashlib import *
import re
from django.http import *
from django.template import loader,RequestContext
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from PIL import Image, ImageDraw, ImageFont, ImageFilter
from io import  StringIO,BytesIO
import random
from user import user_state

# 注册

def register(request):
    return render(request, 'user/register.html')




#  注册结果
def result(request):

    #   验证码验证
    context = {}
    userverification = request.POST.get('userverification')
    if request.session['codes'].upper() == userverification.upper():
        user = User()
        user.uname = request.POST.get('username')
        user.upwd=request.POST.get('userpwd')
        user.uemail = request.POST.get('uemail')
        user.upwd = sha1(user.upwd.encode('utf-8')).hexdigest()
        user.save()

        return HttpResponseRedirect('/user/login')
    else:
        return HttpResponseRedirect('/user/register')

    


#   登录
def login(request):

    #   用户勾选记住用户名时，下次登录调用本地cookies中的用户名
    context = {}
    username = request.COOKIES.get('user_name')
    # 如果用户名在cookie中，返回用户名到登陆界面
    if username:
        context['username']=username
        return render(request, 'user/login.html', context)
    else:
        return render(request,'user/login.html')




#   登录成功
#@csrf_exempt
def success(request):
    context = {}
    username = request.POST.get('username')
    userverification = request.POST.get('userverification')
    if request.session['codes'].upper() == userverification.upper():
        # 使用session实现状态保持
        request.session['currentUser'] = username
        response = HttpResponseRedirect('/goods/index')
        # 获取用户是否选择记住用户名
        remembername = request.POST.get('remembername')
        # 如果选中，将用户名写入cookie中，并设定过期时间
        if remembername=='1':
            response.set_cookie('user_name',username,max_age=3600)
        return response
    else:
        #登陆失败 则重定向至登录界面
        return HttpResponseRedirect('/user/login')



# 验证码生成


def verification(request):
    width = 120
    height = 30
    image = Image.new('RGB',(width,height),(255,255,255))
    font = ImageFont.truetype('/usr/share/fonts/truetype/padauk/Padauk.ttf',26)
    draw = ImageDraw.Draw(image)
    #添加噪点
    for x in range(width):
        for y in range(height):
            draw.point((x,y),fill=rndColor1())
    #设置验证码格式
    codes = ''
    for t in range(4):
        code = rndChar()
        codes += code
        draw.text((30*t + 5,0),code,font=font,fill=rndColor2())
    #images = images.filter(ImageFilter.BLUR)

    request.session['codes'] = codes
    request.session.set_expiry(0)

    f= BytesIO()
    image.save(f,'jpeg')
    return HttpResponse(f.getvalue(),'images/jpeg')

str1 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'

def rndChar():
    return str1[random.randrange(0,len(str1))]
def rndColor1():
    return (random.randint(180, 255), random.randint(180, 255), random.randint(180, 255))
def rndColor2():
    return (random.randint(10, 200), random.randint(10, 200), random.randint(10, 200))



#   验证用户名是否存在
def check_username(request):
    username = request.GET.get('username')
    # 0不存在   1存在
    ret = '0'
    if len(User.objects.filter(uname=username)):
        ret = '1'
    return HttpResponse(ret)

#   验证密码是否正确
def check_userpwd(request):
    # 获取输入的密码，并对输入的密码进行加密
    userpwd = sha1(request.GET.get('userpwd').encode('utf-8')).hexdigest()

    # 0不存在   1存在
    ret = '0'
    if len(User.objects.filter(upwd=userpwd)):
        ret = '1'
    return HttpResponse(ret)


#   验证验证码是否正确
def check_userverification(request):
    # 获取输入的验证码
    userverification = request.GET.get('userverification')
    # 0不正确   1正确
    ret = '1'
    # 如果输入的验证码和session中的验证码不同，返回‘0’
    if request.session['codes'].upper() != userverification.upper():
        ret = '0'
    return HttpResponse(ret)




# 用户个人信息界面
# 装饰器获取session状态，存在则进入个人信息界面，否则跳转至登陆
@user_state.login
def user_center(request):
    user = User.objects.get(uname = request.session['currentUser'])

    goods_list = []
    goods_ids = request.COOKIES.get('goods_ids','')
    if goods_ids != '':
        goods_ids1 = goods_ids.split(',')
        for goods_id in goods_ids1:
            goods_list.append(GoodsInfo.objects.get(id = int(goods_id)))

    context = {
        'user':user,
        'goods_list':goods_list
    }
    return render(request, 'user/user_center.html',context)




# 用户全部订单界面
# 装饰器获取session状态，存在则进入全部订单界面，否则跳转至登陆
@user_state.login
def user_order(request):
    user = User.objects.get(uname = request.session['currentUser'])
    context = {
        'user':user
    }
    return render(request, 'user/user_order.html',context)



# 用户收货地址界面
# 装饰器获取session状态，存在则进入收货地址界面，否则跳转至登陆
@user_state.login
def user_address(request):
    #通过session键获取对象
    #首次访问是以GET方式获取数据 提交是POST方式
    user = User.objects.get(uname = request.session['currentUser'])
    if request.method=='POST':
        post = request.POST
        #获取输入信息，更改并保存至数据库
        user.ureceive = post.get('recipients')
        user.uaddress = post.get('Address')
        user.uzipcode = post.get('postcode')
        user.uphone = post.get('tel')
        user.save()
    # 获取手机号码 对手机号码进行字符串分割,拼接操作
    phone = user.uphone
    uphone = phone[:3]+'****'+phone[7:]
    # 准备上下文，并将上下文发送到收货地址界面
    context = {
        'user':user,
        'uphone':uphone,
    }
    return render(request, 'user/user_address.html',context)




#  退出登陆
def logout(request):
    #清除session缓存
    request.session.flush()
    #跳转至登录界面
    return render(request,'user/login.html')
    # return HttpResponseRedirect('/user/login')

templates/user/login.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>天天生鲜用户登录</title>
    <link rel="stylesheet" type="text/css" href="/static/css/fresh_css.css">
    <script src="/static/js/jquery-1.12.5.js"></script>
    <script type="text/javascript" src="/static/js/jquery.validate.min.js"></script>
    <script src="/static/js/login.js"></script>

{#    更换验证码    #}
    <script type="text/javascript">
        url = '/user/verification'
        function changeImage(obj){
            obj.src =  url+'?num='+new Date()
        }
    </script>

{#    前端验证（点击触发）    #}
{#    <script type="text/javascript">#}
{#        function check() {#}
{#            $("#signForm").validate({#}
{#                rules: {#}
{#                    user: {#}
{#                        required: true,#}
{#                        minlength: 6,#}
{#                        maxlength: 16#}
{#                    },#}
{#                    pwd: {#}
{#                        required: true,#}
{#                        minlength: 6,#}
{#                        maxlength: 16#}
{#                    },#}
{#                },#}
{#                messages: {#}
{#                    user: {#}
{#                        required: "请输入用户名",#}
{#                        minlength: "用户名长度不能小于 6 位",#}
{#                        maxlength: "用户名长度不能大于 16 位"#}
{#                    },#}
{#                    pwd: {#}
{#                        required: "请输入密码",#}
{#                        minlength: "密码长度不能小于 6 位",#}
{#                        maxlength: "密码长度不能大于 16 位"#}
{#                    },#}
{#                }#}
{#            })#}
{#        }#}
{#        $(function(){#}
{#            check()#}
{#            /*$(document).contextmenu(function() {#}
{#                return false;#}
{#            });*/#}
{#            $("#user").focus();#}
{#            })#}
{#    </script>#}

</head>
<body>
<div class="login">
    <form class="cmxform" id="signForm" method="post" action="/user/success">
        {% csrf_token %}
        <div class="login_head">
            <a href="/goods/index" class="brand_logo">
                <img src="/static/image/logo02.png" alt="">
            </a>
        </div>
        <div class="login_body">
            <div class="inside">
                <div class="goods_logo">
                    <img src="/static/image/login_banner.png" alt="">
                </div>
                <div class="note">
                    <p>日夜兼程 · 急速送达</p>
                </div>
                <div class=" log_in">
                    <div class="user_choose">
                        <p class="user_in" >用户登录</p><a class="user_reg" href="/user/register">立即注册</a>
                    </div>
                    <div class="user_enter">
                        <input type="text" id="username" name="username" value="{{ username }}" placeholder="请输入用户名" class="user">
                        <table style="margin-left: 32px">
                            <tr>
                                <td style="color: red;font-size: small"><span id="username_error1" ></span></td>
                            </tr>
                        </table>
                        <input type="password" id="userpwd" name="userpwd" value="" placeholder="请输入密码" class="pwd">
                        <table style="margin-left: 32px">
                            <tr>
                                <td style="color: red;font-size: small"><span id="userpwd_error1" ></span></td>
                            </tr>
                        </table>
                    <div style="text-align: center;width: 312px;margin: 5px auto">
                        <table>
                            <tr>
                                <td><input id="userverification" name="userverification" placeholder="请输入验证码"/></td>
                                <td><img src="/user/verification" alt="验证码" style="cursor: pointer;margin-left: 34px" onclick="changeImage(this)"/></td>
                            </tr>
                        </table>
                        <table>
                            <tr>
                                <td style="color: red;font-size: small"><span id="userverification_error1">{{ userverification_error }}</span></td>
                            </tr>
                        </table>
                    </div>
                        <div class="choose">
                            <input type="checkbox" id="check" class="check" name="remembername" value="1"><label for="check" class="label1">记住用户名</label>
                            <a class="forget" href="#">忘记密码</a>
                        </div>
                        <input type="submit" class="enter_sub" value="登录">
                    </div>
                </div>
            </div>
        </div>
        <div class="foot">
            <div class="link">
                <a href="#">关于我们</a>&nbsp; | &nbsp;
                <a href="#">联系我们</a>&nbsp; | &nbsp;
                <a href="#">招聘人才</a>&nbsp; | &nbsp;
                <a href="#">友情链接</a>
            </div>
            <div class="copy-right">
                <p> Copyright © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
            </div>
            <div class="tel">
                <p>电话：01-****888 京ICP备*******8号</p>
            </div>
        </div>
    </form>
</div>
</body>
</html>

templates/user/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>天天生鲜注册界面</title>
    <link rel="stylesheet" type="text/css" href="/static/css/fresh_css.css">
    <script src="/static/js/jquery-1.12.5.js"></script>
    <script src="/static/js/register.js"></script>
    <script type="text/javascript" src="/static/js/jquery.validate.min.js"></script>
    <script type="text/javascript">
{#        function check() {#}
{#            $("#signupForm").validate({#}
{#                rules: {#}
{#                    User: {#}
{#                        required: true,#}
{#                        minlength: 6,#}
{#                        maxlength: 16#}
{#                    },#}
{#                    Password: {#}
{#                        required: true,#}
{#                        minlength: 6,#}
{#                        maxlength: 16#}
{#                    },#}
{#                    Confirm: {#}
{#                        required: true,#}
{#                        minlength: 6,#}
{#                        maxlength: 16,#}
{#                        equalTo: "#Password"#}
{#                    },#}
{#                    Email: {#}
{#                        required: true,#}
{#                        email: true#}
{#                    },#}
{#                    /*allow:{#}
{#                        required:checked,}*/#}
{#                },#}
{#                messages: {#}
{#                    User: {#}
{#                        required: "请输入用户名",#}
{#                        minlength: "用户名长度不能小于 6 位",#}
{#                        maxlength: "用户名长度不能大于 16 位"#}
{#                    },#}
{#                    Password: {#}
{#                        required: "请输入密码",#}
{#                        minlength: "密码长度不能小于 6 位",#}
{#                        maxlength: "密码长度不能大于 16 位"#}
{#                    },#}
{#                    Confirm: {#}
{#                        required: "请输入密码",#}
{#                        minlength: "密码长度不能小于 6 位",#}
{#                        maxlength: "密码长度不能大于 16 位",#}
{#                        equalTo: "两次密码输入不一致"#}
{#                    },#}
{#                    Email: "邮箱无效，请重新输入",#}
{#                    allow:"同意协议，方可注册"#}
{#                }#}
{#            })#}
{#        }#}
        $(function(){
            var error_check = false;
            $('#allow').click(function() {
                if($(this).is(':checked'))
                {
                    error_check = false;
                    $(this).siblings('span').hide();
                }
                else
                {
                    error_check = true;
                    $(this).siblings('span').html('请勾选同意');
                    $(this).siblings('span').show();
                }
            });
            $('#reg_form').submit(function() {
                if(error_check == false)
                {
                    return true;
                }
                else
                {
                    return false;
                }

            });
            //check()
{#            $(document).contextmenu(function() {#}
{#                return false;#}
{#            });#}
            $("#User").focus();

        })

    </script>


</head>
<body>
<div class="register">
    <form class="cmxform2" id="signupForm" method="post" action="/user/result">
        {% csrf_token %}
        <div class="register_body">
            <div class="inside_reg">
                <div class="web_logo">
                    <a href="/goods/index">
                    <img src="/static/image/logo02.png" alt=""></a>
                    <div class="register_note">
                        <p>足不出户 · 新鲜每一天</p>
                    </div>
                    <img src="/static/image/register_banner.png" alt="">
                </div>
                <div class="new_log_in">
                    <div class="new_user_choose">
                        <p class="new_user" >用户注册</p><a class="user_login" href="/user/login">登录</a>
                    </div>
                    <div class="user_register">
                        <ul class="reg_ul">
                            <li>
                                <span>用户名：</span>
                                <input type="text" id="username" name="username" value="" class="reg_user">
                                <span id="username_error" ></span>
                            </li>
                            <li>
                                <span>密码：</span>
                                <input type="password" id="Password" name="userpwd" value=""class="reg_password">
                                <span id="userpwd_error" ></span>
                            </li>
                            <li>
                                <span>确认密码：</span>
                                <input type="password" id="Confirm" name="Confirm" value=""class="reg_confirm">
                                <span id="userconfirm_error" ></span>
                            </li>
                            <li>
                                <span>邮箱：</span>
                                <input type="text" id="Email" name="uemail" value="" class="reg_email">
                                <span id="useremail_error" ></span>
                            </li>
                            <li>
                                <span>验证码：</span>
                                <input id="userverification" name="userverification" style="width: 100px;float: left;margin-left: 40px"/>
                                <img src="/user/verification" alt="验证码" style="cursor: pointer;margin-left: 29px" onclick="changeImage(this)"/>
                                <span id="userverification_error">{{ userverification_error }}</span>
                            </li>
                        <div class="new_user_check">
                            <input type="checkbox" id="allow" class="allow" checked="checked">
                            <label for="allow" class="label2">同意“天天生鲜用户使用协议”</label>
                            <span class="error_tip2"></span>
                        </div>
                        <input type="submit" class="reg_sub" value="注册">
                    </div>
                </div>
            </div>
        </div>
        <div class="foot">
            <div class="link">
                <a href="#">关于我们</a>&nbsp; | &nbsp;
                <a href="#">联系我们</a>&nbsp; | &nbsp;
                <a href="#">招聘人才</a>&nbsp; | &nbsp;
                <a href="#">友情链接</a>
            </div>
            <div class="copy-right">
                <p> Copyright © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
            </div>
            <div class="tel">
                <p>电话：01-****888 京ICP备*******8号</p>
            </div>
        </div>
    </form>
</div>
</body>
</html>

templates/user/user_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    <script>
        $(function () {
            $('.col04').each(function () {
                var count = $(this).prev().text();
                //　获取商品单价
                var price = $(this).prev().prev().find('span').text();
                console.log(price)
                //  计算小计,结果保留两位小数
                var total0 = parseFloat(count) * parseFloat(price);
                $(this).text(total0.toFixed(2)+'元')
            });
        })
    </script>
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				{% if request.session.currentUser|default:'' != '' %}
                    <div class="login_state"><span>欢迎您：</span><a href="/user/user_center">{{ request.session.currentUser }}</a><span>|</span>
                    <a href="/goods/logout">退出</a></div>
                    {% else %}
                    <div  class="login_in"><a href="/user/login">登录</a><span>|</span>
                    <a href="/user/register">注册</a></div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="/user/user_center">用户中心</a>
					<span>|</span>
					<a href="/shopping_cart/">我的购物车</a>
					<span>|</span>
					<a href="/order/order_list">我的订单</a>
				</div>
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="/goods/index" class="logo fl"><img src="/static/image/logo.png"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<form action="/goods/goods_search" method="get">
                <input type="text" class="input_text fl" name="keyword" {% if keyword %} value="{{ keyword }}" {% else %} placeholder="搜索商品" {% endif %}>
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="/user/user_center">· 个人信息</a></li>
				<li><a href="/order/order_list" class="active">· 全部订单</a></li>
				<li><a href="/user/user_address">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">全部订单</h3>
				{%if paginator.count > 0%}
                {%for order in page%}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{order.odate}}</li>
					<li class="col02">订单号：{{order.oid}}</li>
					<li class="col02 stress">{%if order.oispay%}已支付{%else%}未支付{%endif%}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {%for detail in order.orderdetailinfo_set.all%}
								<ul class="order_goods_list clearfix">
									<li class="col01"><img src="/static/media/{{detail.goodsinfo.gpic}}"></li>
                                    <li class="col02">{{detail.goodsinfo.gtitle|slice:'10'}}<em><span>{{detail.price}}</span>元/{{detail.goodsinfo.gunit}}</em></li>
									<li class="col03">{{detail.count}}</li>
									<li class="col04">0元</li>
								</ul>
                                {%endfor%}
							</td>
							<td width="15%">{{order.ototal}}元</td>
                            {%if order.oispay%}
							<td width="15%">已付款</td>
							<td width="15%"><a href="#" class="oper_btn">查看物流</a></td>
                            {%else%}
                            <td width="15%">待付款</td>
							<td width="15%"><a href="/order/pay{{order.oid}}" class="oper_btn">去付款</a></td>
                            {%endif%}
						</tr>
					</tbody>
				</table>
                {%endfor%}
		        <div class="pagenation">
                    {%if page.has_previous%}
					<a href="/order/order_list{{page.previous_page_number}}"><上一页</a>
					{%endif%}

                    {%for i in paginator.page_range%}
					{%if i == page.number%}
						<a href="" class="active" onclick="return false;">{{i}}</a>
					{%else%}
						<a href="/order/order_list{{i}}">{{i}}</a>
					{%endif%}
				    {%endfor%}

                    {%if page.has_next%}
					<a href="/order/order_list{{page.next_page_number}}">下一页></a>
					{%endif%}
                {%else%}
                暂无订单信息
                {%endif%}
		</div>
	</div>
    </div>



	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	
</body>
</html>